FROM php:8.3-apache

RUN docker-php-ext-install pdo pdo_mysql && \
    a2enmod rewrite

COPY . /var/www/html
COPY public /var/www/html/public

RUN chown -R www-data:www-data /var/www/html && \
    chmod -R 755 /var/www/html/public

WORKDIR /var/www/html
EXPOSE 80
